---
title: "Homework 5 by Ximeng"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Problem 1

Read in the data

```{r}
homicide_df = 
  read_csv("./homicide_data/homicide-data.csv") %>%
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>%
  select(city_state, resolved) %>%
  filter(city_state != "Tulsa_AL")
```

Lets look at this a bit
```{r}
aggregate_df = homicide_df %>%
  group_by(city_state) %>%
  summarise(
    hom_total = n(),
    hom_unsolced = sum(resolved == "unsolved")
  )
```

Can i do prop test for a single city
```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolced),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>%
    broom::tidy()
```

Try to iterate
```{r}
results_df = 
  aggregate_df %>%
  mutate(
    prop_tests = map2(.x = hom_unsolced, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)
```

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2

```{r}
data_1 = read_csv("./lda_data/con_01.csv")
```

```{r}
path_df = 
  tibble(
  path = list.files("lda_data")
  ) %>%
  mutate(path = str_c("lda_data/", path),
         data = map(.x = path, ~read_csv(.x))
  ) %>%
  mutate(
    id = substr(path, 10, 15)
  ) %>%
  unnest(data) %>%
  janitor::clean_names() %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "value"
  ) %>%
  select(-path) %>%
  mutate(
    week = substr(week, 6, 6),
    week = as.numeric(week)
    )
```

## Make spaghetti plot showing observations on each subject over time
```{r}
path_df %>%
  group_by(id) %>%
  ggplot(aes(x = week, y = value, color = id)) + geom_line(alpha = 0.8) + labs(title = "Observation on Each Subject Over Time") + theme_gray() 
```

## Problem 3
```{r}

```



